### ISSUE TITLE
Feat: Support Struct Syncing in Binja

### ISSUE THREAD

**Issue by Lukas-Dresel** [binsync/binsync#122]
Open `phonebook` in binja, sync `person_t` from the `globals` tab

```Traceback (most recent call last):
  File "/home/honululu/lukas/tools/binsync/binsync/common/ui/tables/ctx_table.py", line 110, in <lambda>
    menu.addAction("Sync", lambda: self.controller.fill_function(func_addr, user=username))
  File "/home/honululu/lukas/tools/binsync/binsync/common/controller.py", line 26, in initcheck
    return f(self, *args, **kwargs)
  File "/home/honululu/lukas/tools/binsync/binsync/common/controller.py", line 93, in state_check
    return f(self, *args, **kwargs)
  File "/home/honululu/.binaryninja/plugins/binja_binsync/controller.py", line 159, in fill_function
    type_, _ = bn_func.view.parse_type_string(stack_var.type)
  File "/home/honululu/lukas/tools/binja/binaryninja/plugins/../python/binaryninja/binaryview.py", line 6173, in parse_type_string
    raise SyntaxError(error_str)
SyntaxError: input:1: error: type 'person_t' is not defined
Traceback (most recent call last):
  File "/home/honululu/lukas/tools/binsync/binsync/common/ui/tables/globals_table.py", line 110, in <lambda>
    filler_func = lambda: self.controller.fill_struct(global_name, user=user_name)
  File "/home/honululu/lukas/tools/binsync/binsync/common/controller.py", line 26, in initcheck
    return f(self, *args, **kwargs)
  File "/home/honululu/lukas/tools/binsync/binsync/common/controller.py", line 93, in state_check
    return f(self, *args, **kwargs)
  File "/home/honululu/lukas/tools/binsync/binsync/common/controller.py", line 315, in fill_struct
    raise NotImplementedError
NotImplementedError
```

**Comment by mahaloz** [comment]
Forgot to close this with #201
