### ISSUE TITLE
Artifacts return unexpected types on first connection

### ISSUE THREAD

**Issue by mborgerson** [binsync/binsync#186]
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/binsync/binsync/common/controller.py", line 175, in updater_routine
    self._check_and_notify_ctx()
  File "/opt/binsync/binsync/common/controller.py", line 195, in _check_and_notify_ctx
    self.ctx_change_callback()
  File "/opt/binsync/binsync/common/ui/control_panel.py", line 68, in ctx_callback
    self._ctx_table.update_table(new_ctx=self.controller.last_ctx.addr)
  File "/opt/binsync/binsync/common/ui/panel_tabs/ctx_table.py", line 120, in update_table
    for user in self.controller.users():
TypeError: 'NoneType' object is not iterable

Can happen if host is not known yet and SSH is waiting for accept

**Comment by mahaloz** [comment]
## Solution
This bug is caused by the `cache` and `get_state` and `users` all returning `None` in the event that something goes wrong. In every use of these API we assume that we will at least get a dict. Simply change the return type in all these interfaces.
