### ISSUE TITLE
Cannot pip install in clean python3.6 environment

### ISSUE THREAD

**Issue by zwimer** [binsync/binsync#227]
### Description

`pip install` fails in a clean virtual environment.

It looks like `toml` is an undeclared build dependency? Perhaps `setup.py`'s install mechanism ultimately needs to import `toml`?

If this is the issue, suggestion: add `pyproject.toml` to declare your build dependencies

### Steps to reproduce the bug

```bash
sudo dnf install python3.6 -y
python3.6 -m venv foo
source foo/bin/activate
pip install binsync
```

### Environment

A clean virtual environment of python 3.6

Host OS: `Fedoara 37`

### Additional context

```
zwimer@Quintessential ~> python3.6 -m venv foo
zwimer@Quintessential ~> source foo/bin/activate
(foo) zwimer@Quintessential ~> pip install binsync
piLooking in indexes: https://pypi.org/simple, https://pypi.shellphish.net
Collecting binsync
p fr  Downloading https://files.pythonhosted.org/packages/d6/e4/10d544fa9fb0344966287fdf76d9ae6087904469ef1cbc2e4dbe4afa0f0c/binsync-2.9.6.tar.gz (83kB)
    100% |████████████████████████████████| 92kB 9.5MB/s
ez    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vsykszy5/binsync/setup.py", line 62, in <module>
        setup(cmdclass=cmdclass)
      File "/home/zwimer/foo/lib64/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/home/zwimer/foo/lib64/python3.6/site-packages/setuptools/dist.py", line 567, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/home/zwimer/foo/lib64/python3.6/site-packages/setuptools/config.py", line 120, in parse_configuration
        meta.parse()
      File "/home/zwimer/foo/lib64/python3.6/site-packages/setuptools/config.py", line 406, in parse
        section_parser_method(section_options)
      File "/home/zwimer/foo/lib64/python3.6/site-packages/setuptools/config.py", line 379, in parse_section
        self[name] = value
      File "/home/zwimer/foo/lib64/python3.6/site-packages/setuptools/config.py", line 183, in __setitem__
        value = parser(value)
      File "/home/zwimer/foo/lib64/python3.6/site-packages/setuptools/config.py", line 492, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "/home/zwimer/foo/lib64/python3.6/site-packages/setuptools/config.py", line 329, in _parse_attr
        module = import_module(module_name)
      File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/pip-install-vsykszy5/binsync/binsync/__init__.py", line 14, in <module>
        from binsync.data import *
      File "/tmp/pip-install-vsykszy5/binsync/binsync/data/__init__.py", line 2, in <module>
        from binsync.data.artifact import Artifact
      File "/tmp/pip-install-vsykszy5/binsync/binsync/data/artifact.py", line 3, in <module>
        import toml
    ModuleNotFoundError: No module named 'toml'
    ```

**Comment by zwimer** [comment]
Actually, this seems to require multiple if not all of your runtime dependencies as build dependencies because of that import. I suggest either ensuring your installed does not require those or specify them all as both build and runtime dependencies

**Comment by mahaloz** [comment]
Kk, we should remove all those `import *` from the init
