### ISSUE TITLE
`TypeError`/`AttributeError` somehow related to enums

### ISSUE THREAD

**Issue by alexrp** [binsync/binsync#300]
### Description

```
Exception in thread Thread-8 (_worker_thread):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\core\scheduler.py", line 60, in _worker_thread
    self._complete_a_job(block=True)
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\core\scheduler.py", line 89, in _complete_a_job
    job.execute()
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\core\scheduler.py", line 30, in execute
    self.ret_value = self.function(*self.args, **self.kwargs)
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\core\client.py", line 325, in get_state
    state = State.parse(
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\data\state.py", line 351, in parse
    state.enums = {
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\data\state.py", line 351, in <dictcomp>
    state.enums = {
TypeError: unhashable type: 'list'
```

And a short while later:

```
Exception in thread Thread-6 (_worker_thread):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\core\scheduler.py", line 60, in _worker_thread
    self._complete_a_job(block=True)
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\core\scheduler.py", line 89, in _complete_a_job
    job.execute()
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\core\scheduler.py", line 30, in execute
    self.ret_value = self.function(*self.args, **self.kwargs)
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\api\controller.py", line 32, in _init_check
    return f(self, *args, **kwargs)
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\api\controller.py", line 703, in push_artifact
    was_set = set_artifact_func(state, artifact, set_last_change=set_last_change, **kwargs)
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\data\state.py", line 48, in dirtycheck
    r = f(self, *args, **kwargs)
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\data\state.py", line 118, in _update_last_change
    self.last_push_artifact = artifact_loc
AttributeError: 'dict' object has no attribute 'last_push_artifact'
```

### Steps to reproduce the bug

I'm not actually sure what triggered this. 🤔 Something related to enums, one would assume.

### Environment

Binary Ninja 3.5.4314-dev Personal (6506ee0e)
BinSync 3.10.14

### Additional context

(I don't think this BinSync version has the fix in #298 yet?)

**Comment by alexrp** [comment]
Shortly after this, I started also seeing:

```
WARNING | 2023-06-03 21:25:46,806 | binsync.api.controller | There were no states remote or local.
```

And it seems like syncing stopped working.

**Comment by alexrp** [comment]
Uh oh. I now get this whenever I try to connect to the repo:

```
Exception in thread Thread-8 (_worker_thread):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\core\scheduler.py", line 60, in _worker_thread
    self._complete_a_job(block=True)
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\core\scheduler.py", line 89, in _complete_a_job
    job.execute()
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\core\scheduler.py", line 30, in execute
    self.ret_value = self.function(*self.args, **self.kwargs)
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\core\client.py", line 325, in get_state
    state = State.parse(
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\data\state.py", line 351, in parse
    state.enums = {
  File "C:\Users\alex\AppData\Roaming\Binary Ninja\python310\site-packages\binsync\data\state.py", line 351, in <dictcomp>
    state.enums = {
TypeError: unhashable type: 'list'
```

**Comment by alexrp** [comment]
I have a sneaking suspicion that what happened here is that I deleted a type used by another type and BinSync somehow got into a bad state. 🤔

**Comment by mahaloz** [comment]
@alexrp any chance you can post or direct me to your current .bsproj? I want to see what the `enums.toml` looks like.

**Comment by mahaloz** [comment]
@alexrp any chance this is the repo and this is the commit which triggered the bad bad?
https://github.com/alexrp/tera-eu-387486-binsync/commit/f64563b37c3802aa4f3a972b9af0a3c76aa2c1ca

Looks like somehow an Enum name became a list and not a string.

**Comment by alexrp** [comment]
> any chance this is the repo and this is the commit which triggered the bad bad?

Yep, you got it.
