### ISSUE TITLE
[BinaryNinja] Force push error

### ISSUE THREAD

**Issue by Maxou56800** [binsync/binsync#334]
### Description

Error occur when pressing "Force Push" button in Utilities:

```python
[0:139781527151808 Default error] Traceback (most recent call last):
[0:139781527151808 Default error]   File "/home/user/.binaryninja/python311/site-packages/binsync/ui/panel_tabs/util_panel.py", line 248, in _handle_force_push_button
[0:139781527151808 Default error]     self.popup = ForcePushUI(self.controller)
[0:139781527151808 Default error]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0:139781527151808 Default error]   File "/home/user/.binaryninja/python311/site-packages/binsync/ui/force_push/force_push.py", line 24, in __init__
[0:139781527151808 Default error]     self._update_table_data()
[0:139781527151808 Default error]   File "/home/user/.binaryninja/python311/site-packages/binsync/ui/force_push/force_push.py", line 51, in _update_table_data
[0:139781527151808 Default error]     table.update_table()
[0:139781527151808 Default error]   File "/home/user/.binaryninja/python311/site-packages/binsync/ui/force_push/panels/globals_table.py", line 243, in update_table
[0:139781527151808 Default error]     self.table.update_table()
[0:139781527151808 Default error]   File "/home/user/.binaryninja/python311/site-packages/binsync/ui/force_push/panels/globals_table.py", line 164, in update_table
[0:139781527151808 Default error]     self.model.update_table()
[0:139781527151808 Default error]   File "/home/user/.binaryninja/python311/site-packages/binsync/ui/force_push/panels/globals_table.py", line 95, in update_table
[0:139781527151808 Default error]     self.data_dict[artifact.addr] = [artifact.addr, artifact.name, type_]
[0:139781527151808 Default error]                                      ^^^^^^^^^^^^^
[0:139781527151808 Default error] AttributeError: 'Enum' object has no attribute 'addr'
```

### Steps to reproduce the bug

1) Start binja
2) Open a sample
2) Plugins>Binsync configure..
3) Configure and open a existing git folder
4) Go to the Binsync layout
5) Press "Force Push..."

### Environment

OS: Linux
Binja: 3.5.4525-dev (5c6bbf2c)
Binsync plugin version: 3.13.1

**Comment by mahaloz** [comment]
@Maxou56800 would you be able to share the binary that caused this? Somehow an Enum in your decompiler sneaked into your global variables.

**Comment by Maxou56800** [comment]
Sample sent by private message.

**Comment by mahaloz** [comment]
The Binja Plugin Manager was outdated. Solved offline.
