### ISSUE TITLE
Odd error message

### ISSUE THREAD

**Issue by domenukk** [binsync/binsync#393]
### Description

This happened randomly when trying to checkout some Ida push from Ghidra
```python
[INFO] | ghidra.interface | Starting BinSync artifact watchers...
Traceback (most recent call last):
  File "/Users/dmnk/ghidra_scripts/libbs_vendored/jfx_bridge/bridge.py", line 1365, in local_eval
    result = eval(eval_expr, eval_globals, eval_locals)
  File "<string>", line 1, in <module>
NameError: name 'lowered_addr' is not defined
[ERROR] | ghidra.interface | Failed to evaluate remote code: [             _self.currentProgram.getFunctionManager().getFunctionContaining(_self.flat_api.toAddr(hex(lowered_addr)))         ]
Traceback (most recent call last):
  File "/Users/dmnk/ghidra_scripts/libbs_vendored/jfx_bridge/bridge.py", line 1365, in local_eval
    result = eval(eval_expr, eval_globals, eval_locals)
  File "<string>", line 1, in <module>
NameError: name 'g_enum' is not defined
[ERROR] | ghidra.interface | Failed to evaluate remote code: [             (name, g_enum.getValue(name)) for name in g_enum.getNames()         ]
```

It _might_ be that my git repository had timed out(?) - I did close my laptop in the meatime - but I wanted to report it anyway.

Great project!

### Steps to reproduce the bug

Happened once

**Comment by mahaloz** [comment]
nvm I figured it out from your other issue
